---
- name: Install netdata
  apt:
    pkg:
    - netdata

- name: Ensure configuration directory exists
  file:
    name: "{{ netdata_conf_dir }}"
    state: directory

- name: Copy netdata configuration
  template:
    src: netdata.conf
    dest: "{{ netdata_conf }}"

#- name: Configure alarms
#  template:
#    src: health_alarm_notify.conf
#    dest: /etc/netdata/health_alarm_notify.conf
#    owner: netdata
#    mode: '0644'

- name: Restart netdata
  service:
    name: netdata
    state: restarted
    enabled: true
