---
netdata_install_dir: /opt
netdata_systemd: True
netdata_deps:
  - zlib1g-dev
  - uuid-dev
  - libmnl-dev
  - gcc
  - make
  - git
  - autoconf
  - autoconf-archive
  - autogen
  - automake
  - pkg-config
netdata_version: v1.4.0
netdata_service_name: "netdata"

# Fichero de configuración
netdata_conf_dir: "/etc/netdata"
netdata_conf: "{{ netdata_conf_dir }}/netdata.conf"
